2025-03-14 13:58:20,530 INFO    MainThread:3939703 [wandb_setup.py:_flush():67] Current SDK version is 0.19.7
2025-03-14 13:58:20,530 INFO    MainThread:3939703 [wandb_setup.py:_flush():67] Configure stats pid to 3939703
2025-03-14 13:58:20,531 INFO    MainThread:3939703 [wandb_setup.py:_flush():67] Loading settings from /mnt/home/jgaber/.config/wandb/settings
2025-03-14 13:58:20,531 INFO    MainThread:3939703 [wandb_setup.py:_flush():67] Loading settings from /mnt/home/jgaber/LORR24_johannesg98/wandb/settings
2025-03-14 13:58:20,531 INFO    MainThread:3939703 [wandb_setup.py:_flush():67] Loading settings from environment variables
2025-03-14 13:58:20,531 INFO    MainThread:3939703 [wandb_init.py:setup_run_log_directory():647] Logging user logs to /mnt/home/jgaber/LORR24_johannesg98/wandb/run-20250314_135820-oqoewpu3/logs/debug.log
2025-03-14 13:58:20,531 INFO    MainThread:3939703 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to /mnt/home/jgaber/LORR24_johannesg98/wandb/run-20250314_135820-oqoewpu3/logs/debug-internal.log
2025-03-14 13:58:20,531 INFO    MainThread:3939703 [wandb_init.py:init():761] calling init triggers
2025-03-14 13:58:20,531 INFO    MainThread:3939703 [wandb_init.py:init():766] wandb.init called with sweep_config: {}
config: {'name': 'sac', 'agent_name': '20250314_sac_gnn', 'cplexpath': 'None', 'directory': 'saved_files', 'max_episodes': 20000, 'max_steps': 150, 'no_cuda': False, 'batch_size': 100, 'p_lr': 0.001, 'q_lr': 0.001, 'alpha': 0.3, 'auto_entropy': False, 'hidden_size': 256, 'clip': 500, 'checkpoint_path': 'SAC_A**20_20000', 'load_from_ckeckpoint': False, 'use_LSTM': False, 'input_size': 3, 'test_episodes': 10, 'determinisitc_backup': False, 'pretrained_path': None, 'only_q_steps': 0, 'wandb': True, 'tensorboard': True, 'mask_impactless_actions': True, '_wandb': {}}
2025-03-14 13:58:20,531 INFO    MainThread:3939703 [wandb_init.py:init():784] starting backend
2025-03-14 13:58:20,531 INFO    MainThread:3939703 [wandb_init.py:init():788] sending inform_init request
2025-03-14 13:58:20,538 INFO    MainThread:3939703 [backend.py:_multiprocessing_setup():97] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2025-03-14 13:58:20,539 INFO    MainThread:3939703 [wandb_init.py:init():803] backend started and connected
2025-03-14 13:58:20,545 INFO    MainThread:3939703 [wandb_init.py:init():896] updated telemetry
2025-03-14 13:58:20,573 INFO    MainThread:3939703 [wandb_init.py:init():920] communicating run to backend with 90.0 second timeout
2025-03-14 13:58:20,812 ERROR   MainThread:3939703 [wandb_init.py:init():1481] error in wandb.init()
Traceback (most recent call last):
  File "/mnt/home/jgaber/miniconda3/envs/myenv/lib/python3.12/site-packages/wandb/sdk/wandb_init.py", line 1471, in init
    return wi.init(run_settings, run_config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/home/jgaber/miniconda3/envs/myenv/lib/python3.12/site-packages/wandb/sdk/wandb_init.py", line 968, in init
    raise error
wandb.errors.errors.CommError: failed to upsert bucket: returned error 400 Bad Request: {"errors":[{"message":"you may not log runs directly to your organization, please try using your team entity","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2025-03-14 13:58:20,886 WARNING MsgRouterThr:3939703 [router.py:message_loop():77] message_loop has been closed
Traceback (most recent call last):
  File "/mnt/home/jgaber/miniconda3/envs/myenv/lib/python3.12/site-packages/wandb/sdk/interface/router_sock.py", line 28, in _read_message
    resp = self._sock_client.read_server_response(timeout=1)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/home/jgaber/miniconda3/envs/myenv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 285, in read_server_response
    data = self._read_packet_bytes(timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/home/jgaber/miniconda3/envs/myenv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 270, in _read_packet_bytes
    raise SockClientClosedError
wandb.sdk.lib.sock_client.SockClientClosedError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/mnt/home/jgaber/miniconda3/envs/myenv/lib/python3.12/site-packages/wandb/sdk/interface/router.py", line 70, in message_loop
    msg = self._read_message()
          ^^^^^^^^^^^^^^^^^^^^
  File "/mnt/home/jgaber/miniconda3/envs/myenv/lib/python3.12/site-packages/wandb/sdk/interface/router_sock.py", line 30, in _read_message
    raise MessageRouterClosedError from e
wandb.sdk.interface.router.MessageRouterClosedError
2025-03-14 13:58:20,890 INFO    MsgRouterThr:3939703 [mailbox.py:close():115] Closing mailbox, abandoning 0 handles.
