2025-02-24 23:02:36,095 INFO    MainThread:27390 [wandb_setup.py:_flush():67] Current SDK version is 0.19.7
2025-02-24 23:02:36,095 INFO    MainThread:27390 [wandb_setup.py:_flush():67] Configure stats pid to 27390
2025-02-24 23:02:36,096 INFO    MainThread:27390 [wandb_setup.py:_flush():67] Loading settings from /home/johannes/.config/wandb/settings
2025-02-24 23:02:36,096 INFO    MainThread:27390 [wandb_setup.py:_flush():67] Loading settings from /home/johannes/masterarbeit/LORR24_johannesg98/wandb/settings
2025-02-24 23:02:36,096 INFO    MainThread:27390 [wandb_setup.py:_flush():67] Loading settings from environment variables
2025-02-24 23:02:36,096 INFO    MainThread:27390 [wandb_init.py:setup_run_log_directory():647] Logging user logs to /home/johannes/masterarbeit/LORR24_johannesg98/wandb/offline-run-20250224_230236-tcemd15r/logs/debug.log
2025-02-24 23:02:36,096 INFO    MainThread:27390 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to /home/johannes/masterarbeit/LORR24_johannesg98/wandb/offline-run-20250224_230236-tcemd15r/logs/debug-internal.log
2025-02-24 23:02:36,096 INFO    MainThread:27390 [wandb_init.py:init():761] calling init triggers
2025-02-24 23:02:36,096 INFO    MainThread:27390 [wandb_init.py:init():766] wandb.init called with sweep_config: {}
config: {'name': 'a2c', 'agent_name': '20250224_sac_gnn', 'cplexpath': 'None', 'directory': 'saved_files', 'max_episodes': 1000, 'max_steps': 150, 'no_cuda': False, 'batch_size': 100, 'p_lr': 0.001, 'q_lr': 0.001, 'hidden_size': 256, 'clip': 500, 'checkpoint_path': 'A2C', 'load_from_ckeckpoint': False, 'input_size': 3, 'test_episodes': 10, 'wandb': True, '_wandb': {}}
2025-02-24 23:02:36,096 INFO    MainThread:27390 [wandb_init.py:init():784] starting backend
2025-02-24 23:02:36,301 ERROR   MainThread:27390 [wandb_init.py:init():1481] error in wandb.init()
Traceback (most recent call last):
  File "/home/johannes/masterarbeit/LORR24_johannesg98/RL/venv/lib/python3.12/site-packages/wandb/sdk/wandb_init.py", line 1471, in init
    return wi.init(run_settings, run_config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/johannes/masterarbeit/LORR24_johannesg98/RL/venv/lib/python3.12/site-packages/wandb/sdk/wandb_init.py", line 787, in init
    service = self._wl.ensure_service()
              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/johannes/masterarbeit/LORR24_johannesg98/RL/venv/lib/python3.12/site-packages/wandb/sdk/wandb_setup.py", line 264, in ensure_service
    self._connection = service_connection.connect_to_service(self._settings)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/johannes/masterarbeit/LORR24_johannesg98/RL/venv/lib/python3.12/site-packages/wandb/sdk/lib/service_connection.py", line 40, in connect_to_service
    return _start_and_connect_service(settings)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/johannes/masterarbeit/LORR24_johannesg98/RL/venv/lib/python3.12/site-packages/wandb/sdk/lib/service_connection.py", line 80, in _start_and_connect_service
    client.connect(port)
  File "/home/johannes/masterarbeit/LORR24_johannesg98/RL/venv/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 102, in connect
    s.connect(("localhost", port))
ConnectionRefusedError: [Errno 111] Connection refused
